version: "3.9"

services:

  biling-postgres:
    image: postgres:14
    restart: always
    container_name: biling-postgres
    environment:
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./initial.sql:/docker-entrypoint-initdb.d/initial.sql

  biling-jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: biling-jaeger
    restart: always
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
